"use strict";
var adapters = require("./lib/adapters");
exports.adapters = adapters;
var animators = require("./lib/animators");
exports.animators = animators;
var base = require("./lib/base");
exports.base = base;
var bounds = require("./lib/bounds");
exports.bounds = bounds;
var controllers = require("./lib/controllers");
exports.controllers = controllers;
var display = require("./lib/display");
exports.display = display;
var draw = require("./lib/draw");
exports.draw = draw;
var errors = require("./lib/errors");
exports.errors = errors;
var events = require("./lib/events");
exports.events = events;
var factories = require("./lib/factories");
exports.factories = factories;
var graphics = require("./lib/graphics");
exports.graphics = graphics;
var managers = require("./lib/managers");
exports.managers = managers;
var materials = require("./lib/materials");
exports.materials = materials;
var partition = require("./lib/partition");
exports.partition = partition;
var pick = require("./lib/pick");
exports.pick = pick;
var prefabs = require("./lib/prefabs");
exports.prefabs = prefabs;
var text = require("./lib/text");
exports.text = text;
var textures = require("./lib/textures");
exports.textures = textures;
var utils = require("./lib/utils");
exports.utils = utils;
var View_1 = require("./lib/View");
exports.View = View_1.View;
partition.PartitionBase.registerAbstraction(partition.CameraNode, display.Camera);
partition.PartitionBase.registerAbstraction(partition.DirectionalLightNode, display.DirectionalLight);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.Sprite);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.Shape);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.MovieClip);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.Billboard);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.LineSegment);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.TextField);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.TextFieldMultiRender);
partition.PartitionBase.registerAbstraction(partition.LightProbeNode, display.LightProbe);
partition.PartitionBase.registerAbstraction(partition.PointLightNode, display.PointLight);
partition.PartitionBase.registerAbstraction(partition.SkyboxNode, display.Skybox);
