
export const enum TimelineActionType{
	UPDATE_MTX=1,
	UPDATE_CMTX=2,
	UPDATE_MASKS=3,
	UPDATE_NAME=4,
	UPDATE_BUTTON_NAME=5,
	UPDATE_VISIBLE=6,
	UPDATE_BLENDMODE=7,
	UPDATE_RENDERMODE=8,
	UPDATE_FILTERS=9,
	UPDATE_SCALE_ROT=11,
	UPDATE_POS=12,
	ENABLE_MASKMODE=200,
	REMOVE_MASK=201,
	SWAP_GRAPHICS=202,
	SET_RATIO=203,
	START_AUDIO=204,
}